part of app_themes;

final darkTheme = FlexThemeData.dark(
  colorScheme: darkColorScheme,
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 6,
  fontFamily: FontAssets.poppins,
  appBarElevation: 0.3,
  appBarStyle: FlexAppBarStyle.background,
  subThemesData: const FlexSubThemesData(
    //   useFlutterDefaults: true,
    blendOnLevel: 30,
    blendTextTheme: false,
    useTextTheme: false,
    textButtonRadius: 8,
    elevatedButtonRadius: 8,
    outlinedButtonRadius: 8,
    toggleButtonsRadius: 8,
    inputDecoratorRadius: 12,
    inputDecoratorUnfocusedHasBorder: false,
    fabRadius: 12,
    chipSchemeColor: SchemeColor.primary,
    cardRadius: 8,
    popupMenuRadius: 6,
    dialogBackgroundSchemeColor: SchemeColor.onSecondary,
    inputDecoratorSchemeColor: SchemeColor.onInverseSurface,
    dialogRadius: 18,
    timePickerDialogRadius: 18,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
).copyWith(
  inputDecorationTheme: _textInputDecorationTheme(isDarkMode: true),
  elevatedButtonTheme: _elevatedButtonTheme(),
  pageTransitionsTheme: _cupertionPageTransition(),
);
